### ISSUE TITLE
Can't read files saved from MidiEditor

### ISSUE THREAD

**Issue by Meekohi** [abreheret/MidiEditor#19]
Files I'm saving from MidiEditor can't be read by other programs. 👎
Example at https://www.dropbox.com/s/udl55azw8shkj8r/test5.mid?dl=0

**Comment by easyaspi314** [comment]
Please provide more info, such as
- What OS and compiler did you use?
- Did you compile from master or use a prebuilt release?
- What programs did you try it in?
- Can you reopen it in MidiEditor?

**Comment by Meekohi** [comment]
Windows 64bit prebuilt release version 3.1.2
Running on Windows 10

Tried file in Windows Media Player (Windows 10) and Garage Band (recent OSX).

**Comment by Meekohi** [comment]
Does not re-open in MidiEditor (program freezes)

**Comment by easyaspi314** [comment]
Try building from master.

Past builds have had issues with occasional corruption.

**Comment by abreheret** [comment]
I think the bug happens when the file is saved. test the news version patched (in attachement - Windows 64bit) and tell me if it do works to close the issue and create new tag version.

[MidiEditor_x64_v3.1.2-5-gd6772b1.zip](https://github.com/abreheret/MidiEditor/files/1713336/MidiEditor_x64_v3.1.2-5-gd6772b1.zip)

**Comment by abreheret** [comment]
New version fix this bug. Binaries for windows available here : https://github.com/abreheret/MidiEditor/releases

**Comment by Meekohi** [comment]
Thanks!
